config/routes.rb
Rails.application.routes.draw do
  root to: proc { [404, {}, ['']]}
  resources :job_boards, only: [:index, :show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord
    belongs_to :job_board, optional: true
end

app/models/job_board.rb
class JobBoard < ApplicationRecord
    has_many :jobs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/job_boards_controller.rb
class JobBoardsController < ApplicationController
  before_action :set_job_board, only: %i[ show edit update destroy ]

  # GET /job_boards or /job_boards.json
  def index
    @job_boards = JobBoard.all
  end

  # GET /job_boards/1 or /job_boards/1.json
  def show
    job_board = JobBoard.find(params[:id])
    # Relationship is needed, buts let's see if we can do it without one for now.
    @jobs = job_board.jobs
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_job_board
      @job_board = JobBoard.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def job_board_params
      params.require(:job_board).permit(:name, :rating, :root_domain, :logo_location, :description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/job_boards_helper.rb
module JobBoardsHelper
end

app/helpers/jobs_helper.rb
module JobsHelper
end

app/views/job_boards/index.html.erb
<div class="container">
  <h1>Job Boards</h1>
  <div class="card-deck">
    <% @job_boards.each do |job_board| %>
        <div class="card">
          <a href="job_boards/<%= job_board.id %>"><span></span></a>
            <div class="card-header">
              <div class="text-right">
                <span class=<%= job_board.rating.downcase %>><%= job_board.rating %></span>
              </div>
            </div>
              <div class="card-body">
                <div class="row">
                  <div class="col-3">
                    <img src=<%= job_board.logo_location %> alt=<%= job_board.name %>>
                  </div>
                  <div class="col-9"><%= job_board.description %></div>
                </div>
              </div>
          </div>
    <%end%>
  </div>
</div>

app/views/job_boards/show.html.erb
<div class="container">
  <h1>Job Board</h1>

  <table class="table">
    <thead>
      <tr>
        <th>ID</th>
        <th>Job title</th>
        <th>Company name</th>
        <th>Job url</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @jobs.each do |job| %>
        <tr>
          <td><%= job.id %>
          <td><%= job.job_title %></td>
          <td><%= job.company_name %></td>
          <td><%= job.job_url %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Back', job_boards_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TakeHome</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>